[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/cotizaciones"
  to = "/.netlify/functions/cotizaciones"
  status = 200

[[redirects]]
  from = "/api/mundo"
  to = "/.netlify/functions/mundo"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
